#!/bin/bash

if [ $# -ne 1 ]; then
    echo "사용법: $0 <BOJ 문제 번호>"
    exit 1
fi

boj_number="$1"

# test 폴더의 경우 코드 초기화
if [ "$boj_number" = "test" ]; then
    cp -r $(dirname $0)/template/* "test/"
    chmod 777 -R "test/"
    echo "==== test 폴더 초기화 ===="
    exit 0
fi

if [ -d "$boj_number" ]; then
    echo "$boj_number번 문제가 이미 존재합니다."
    exit 0
fi

mkdir -p "$boj_number"

cp -r $(dirname $0)/template/* "$boj_number/"

# root 권한으로 생성된 경우 권한 변경
if [ $(id -u) -eq 0 ]; then
    chmod 777 -R "$boj_number/"
fi

echo "==== $boj_number번 추가됨 ===="
