#!/bin/bash

if [ $# = 1 ]; then
    if [ "$1" = "-h" ]; then
        manual="
            이 스크립트는 Backjoon Online Judge에서 C++ 소스 코드를 컴파일하고 실행하는 데 도움을 줍니다.
            
            \033[1m사용법:\033[0m
            1. 소스 코드를 컴파일하고 실행하기:
               $0 <BOJ 문제 번호>
               예: $0 12345

            2. 입력 파일을 사용하여 소스 코드를 컴파일하고 실행하기:
               $0 -f <BOJ 문제 번호>
               예: $0 -f 12345

            3. 이 도움말 메시지 표시:
               $0 -h

            \033[1m옵션:\033[0m
            -h     : 이 도움말 메시지 표시
            -f     : 입력 파일 (input.txt)을 사용하여 실행

            본 스크립트는 주어진 BOJ 문제 번호와 소스 코드를 컴파일하고 실행합니다.
            실행이 완료되면 컴파일된 실행 파일을 삭제합니다.
        "
        echo -e "$manual"
        exit 0
    fi

    cpp_file="$1/main.cpp"
    output_file="${cpp_file%.*}"

    if g++ "$cpp_file" -o "$output_file"; then
        echo "==== 컴파일 성공 ===="

        "./$output_file"

        # 실행이 완료되면 컴파일된 실행 파일을 삭제
        rm -f "$output_file"
    else
        echo "==== 컴파일 실패 ===="
    fi

elif [ $# = 2 ]; then
    if [ "$1" = "-f" ]; then
        cpp_file="$2/main.cpp"
        output_file="${cpp_file%.*}"
        input_data=$(cat input.txt)

        if g++ "$cpp_file" -o "$output_file"; then
            echo "==== 컴파일 성공 ===="

            "./$output_file" <<< "$input_data"

            echo -e "\n====================="

            # 실행이 완료되면 컴파일된 실행 파일을 삭제
            rm -f "$output_file"
        else
            echo "==== 컴파일 실패 ===="
        fi

    else 
        echo "사용법: $0 <옵션> <BOJ 문제 번호>"
        exit 1
    fi
else    
    echo "사용법: $0 <BOJ 문제 번호>"
    exit 1
fi